# Generated by Django 5.1 on 2024-10-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('seedbeds', '0002_remove_seedbed_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedbed',
            name='community',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='seedbeds', to='communities.community'),
            preserve_default=False,
        ),
    ]
