# Generated by Django 5.1 on 2024-10-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedbeds', '0003_seedbed_community'),
        ('seedbeds', '0003_seedbed_community_seedbed_product'),
    ]

    operations = [
    ]
