# Generated by Django 5.1 on 2024-10-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_seedbeds'),
        ('seedbeds', '0004_merge_20241015_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedbed',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seedbeds_in_community', to='communities.community'),
        ),
    ]
