# Generated by Django 5.1 on 2024-10-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedbeds', '0005_alter_seedbed_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedbed',
            name='product',
        ),
    ]
