# Generated by Django 5.1 on 2024-10-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('seedbeds', '0006_remove_seedbed_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedbed',
            name='community',
        ),
        migrations.AddField(
            model_name='seedbed',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seedbeds', to='areas.area'),
        ),
    ]
