# Generated by Django 5.1.1 on 2024-10-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('seedbeds', '0002_remove_seedbed_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='seedbeds',
            field=models.ManyToManyField(related_name='communities', to='seedbeds.seedbed'),
        ),
    ]
