# Generated by Django 5.1.1 on 2024-11-14 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_membershiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
