# Generated by Django 5.1.1 on 2024-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_membershiprequest_request_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershiprequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='membership_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
