# Generated by Django 5.1.1 on 2024-11-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_membershiprequest_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='membership_date',
        ),
    ]
