# Generated by Django 5.1.1 on 2024-11-26 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_remove_membershiprequest_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='invite_date',
        ),
        migrations.RemoveField(
            model_name='sendcommunityinvite',
            name='request_date',
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sendcommunityinvite',
            name='invite_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
