# Generated by Django 5.1.1 on 2024-11-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_sendcommunityinvite_requested_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
