# Generated by Django 5.1 on 2024-09-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_nascimento',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='estado',
            new_name='state',
        ),
    ]
