# Generated by Django 5.1 on 2024-09-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_data_nascimento_user_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
