# Generated by Django 5.1.1 on 2024-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'A Fazer'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída')], default='to_do', max_length=15),
        ),
    ]
