# Generated by Django 5.1.1 on 2024-11-23 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_initial'),
        ('communities', '0006_remove_membershiprequest_membership_date'),
        ('products', '0001_initial'),
        ('seedbeds', '0002_seedbed_area'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_tasks', to='areas.area'),
        ),
        migrations.AddField(
            model_name='task',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_tasks', to='communities.community'),
        ),
        migrations.AddField(
            model_name='task',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='local',
            field=models.CharField(choices=[('community', 'Comunidade'), ('area', 'Área'), ('seedbed', 'Canteiro'), ('product', 'Cultivo'), ('type_product', 'Tipo Cultivo')], default='community', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='seedbed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seedbed_tasks', to='seedbeds.seedbed'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'Pendente'), ('in_progress', 'Progresso'), ('completed', 'Concluída')], default='to_do', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_product_tasks', to='products.typeproduct'),
        ),
        migrations.AlterField(
            model_name='task',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tasks', to='products.product'),
        ),
    ]
