# Generated by Django 5.1.1 on 2024-11-24 13:33

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_deadline_remove_task_recurrence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='materials',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('unique', 'Única'), ('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], default='unique', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'Pendente'), ('in_progress', 'Progresso'), ('completed', 'Concluída')], default='to_do', max_length=20),
        ),
    ]
