# Generated by Django 5.1.1 on 2024-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_materials_task_recurrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
