# Generated by Django 5.1.1 on 2024-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'A Fazer'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída')], default='to-do', max_length=20, null=True),
        ),
    ]
