# Generated by Django 5.1.1 on 2024-11-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'Pendente'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída')], default='to-do', max_length=20, null=True),
        ),
    ]
