# Generated by Django 5.1 on 2024-10-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('seedbeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_products', to='communities.community')),
            ],
            options={
                'unique_together': {('name', 'community')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField()),
                ('quantidade', models.IntegerField(default=1)),
                ('seedbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_seedbed', to='seedbeds.seedbed')),
                ('type_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeproduct')),
            ],
        ),
    ]
