# Generated by Django 5.1.1 on 2024-11-14 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_typeproduct_lifecycle'),
        ('seedbeds', '0002_seedbed_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='total_colhido',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_date', models.DateField(default=django.utils.timezone.now)),
                ('seedbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='seedbeds.seedbed')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='products.typeproduct')),
            ],
        ),
    ]
