# Generated by Django 5.1.1 on 2024-10-03 13:42

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_data_plantio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nome',
        ),
        migrations.AddField(
            model_name='product',
            name='data_plantio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
