# Generated by Django 5.1.1 on 2024-11-14 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_typeproduct_total_colhido_harvest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='harvest',
            name='data_colheita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='harvest',
            name='quantidade_colhida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
