# Generated by Django 5.1.1 on 2024-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_harvest_harvest_date_remove_harvest_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='actions_interval',
            field=models.JSONField(default=dict),
        ),
    ]
