# Generated by Django 5.1.1 on 2024-10-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_typeproduct_alter_product_data_plantio_product_nome'),
        ('seedbeds', '0002_remove_seedbed_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canteiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='seedbeds.seedbed'),
        ),
    ]
