# Generated by Django 5.1.1 on 2024-11-22 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_typeproduct_actions_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_colheita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='quantidade_colhida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
    ]
