# Generated by Django 5.1.1 on 2024-11-22 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_data_colheita_product_quantidade_colhida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_colheita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_plantio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
