# Generated by Django 5.1.1 on 2024-10-15 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_seedbeds'),
        ('products', '0006_remove_product_canteiro_product_seedbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='communities.community'),
        ),
    ]
