# Generated by Django 5.1.1 on 2024-10-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_community'),
        ('seedbeds', '0002_remove_seedbed_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seedbed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_seedbed', to='seedbeds.seedbed'),
        ),
    ]
