# Generated by Django 5.1.1 on 2024-11-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_data_colheita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantidade_colhida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
