# Generated by Django 5.1.1 on 2024-11-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_quantidade_colhida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_colheita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.typeproduct'),
        ),
    ]
