# Generated by Django 5.1.1 on 2024-10-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_seedbed'),
        ('seedbeds', '0003_seedbed_community_seedbed_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seedbed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_seedbed', to='seedbeds.seedbed'),
        ),
    ]
