# Generated by Django 5.1.1 on 2024-10-15 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_seedbed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeproduct',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='data_plantio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeproduct', to_field='name'),
        ),
    ]
