# Generated by Django 5.1.1 on 2024-11-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_data_colheita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='taxa_colheita',
            field=models.FloatField(default=1.0),
        ),
    ]
