# Generated by Django 5.1.1 on 2024-10-15 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_seedbeds'),
        ('products', '0010_rename_nome_typeproduct_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_products', to='communities.community'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeproduct'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='typeproduct',
            unique_together={('name', 'community')},
        ),
    ]
