# Generated by Django 5.1.1 on 2024-11-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_typeproduct_taxa_colheita'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_harvested',
            field=models.BooleanField(default=False),
        ),
    ]
