# Generated by Django 5.1 on 2024-10-15 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_typeproduct_community_alter_product_type_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_plantio',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 10, 15, 9, 34, 2, 265590, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
