# Generated by Django 5.1.1 on 2024-11-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_is_harvested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_harvested',
        ),
    ]
