# Generated by Django 5.1 on 2024-10-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_data_plantio_product_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='community',
        ),
    ]
