# Generated by Django 5.1.1 on 2024-11-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_is_harvested'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_harvested',
            field=models.BooleanField(default=False),
        ),
    ]
