# Generated by Django 5.1.1 on 2024-11-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_is_harvested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_harvested',
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('products_in_seedbed', models.ManyToManyField(related_name='harvests', to='products.product')),
            ],
        ),
    ]
