# Generated by Django 5.1 on 2024-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_plantio',
            field=models.DateField(),
        ),
    ]
