# Generated by Django 5.1.1 on 2024-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_is_harvested_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comentario',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
