# Generated by Django 5.1.1 on 2024-09-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data_plantio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='necessidade_manejo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantidade',
        ),
    ]
