# Generated by Django 5.1.1 on 2024-10-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_especie_remove_product_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='data_plantio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeproduct', to_field='nome'),
        ),
    ]
